general.import = ["~/.config/alacritty/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10
offset = { y = 15 }
glyph_offset.y = 5

[window]
decorations = "None"
opacity = 0.9
blur = true

[selection]
save_to_clipboard = true

[cursor]
style = { blinking = "On" }

[terminal]
osc52 = "CopyPaste"
